### ISSUE TITLE
Add publication based on this dataset (LightPIR)

### ISSUE THREAD

**Issue by s-tikhomirov** [lnresearch/topology#10]
LightPIR: Privacy-Preserving Route Discovery for Payment Channel Networks

https://arxiv.org/abs/2104.04293

They use the datasets to suggest an optimized hub labeling protocol for a more efficient graph pre-processing (and combined with private information retrieval for privacy).

**Comment by cdecker** [comment]
This was addressed in c4539bdc8f922eb42696a9fa14acfac524aebda6
