### ISSUE TITLE
Snapshot 20220719 not found

### ISSUE THREAD

**Issue by Pantamis** [lnresearch/topology#15]
Hi !

The page https://storage.googleapis.com/lnresearch/gossip-20220719.gsp.bz2 says "no such key", I can't download the snapshot.

The others works well so maybe it is an issue with the name ? I don't have the permission to get the list of objects in lnreasearch bucket.

Thanks for the marvelous data :)

**Comment by cdecker** [comment]
It was incomplete causing the following error:

```
ValueError: Error reading dataset at 2552794999: incomplete read of 138 bytes, only got 136 bytes
```

It was replaced by snapshot `gossip-20220823.gsp.bz2`, we just forgot to remove it from the index.
