### ISSUE TITLE
Is it possible to provide the code to decode the raw message?

### ISSUE THREAD

**Issue by Mitsuhamizu** [lnresearch/topology#3]
If the code for decoding can be provided, I think it will be very convenient for many people.

**Comment by cdecker** [comment]
Certainly, it's already available here https://github.com/lnresearch/topology/blob/main/cli/parser.py

**Comment by cdecker** [comment]
Let me know if I should put it somewhere more prominent.

**Comment by ZhichunLu-11** [comment]
> Certainly, it's already available here https://github.com/lnresearch/topology/blob/main/cli/parser.py

Thank you very much for your answer! And thank you for providing such great data! 

By the way, do you have time to read this [issue](https://github.com/lightningnetwork/lightning-rfc/issues/822)? I have some confusion about the multi-hop lock time of the Lightning Network RFC.
