### ISSUE TITLE
Unable to load data using script provided.

### ISSUE THREAD

**Issue by defianalytics** [lnresearch/topology#5]
Hi, 

When i try to load the data using both the files below:
DATA_FILE_PATH0 = "data/gossip-20201203.gsp.bz2"
DATA_FILE_PATH1 = "../data/gossip-20210104.gsp.bz2"
DATA_FILE_PATH2 = "../data/gossip-20210908.gsp.bz2"

There are errors  For the Files 
DATA_FILE_PATH0===>  ValueError: Incomplete message read from
DATA_FILE_PATH1===>ValueError: Incomplete message read 
DATA_FILE_PATH2===> ValueError: OS error respectively 

May I know if I am using the below script to load data is good to go

======= SCRIPT===========
```
from pyln.proto.primitives import varint_decode
import bz2

def read_dataset(filename: str):
    print("Reading File")
    with bz2.open(filename, 'rb') as f:
        header = f.read(4)
        assert(header[:3] == b'GSP' and header[3] == 1)
        while True:
            length = varint_decode(f)
            msg = f.read(length)
            if len(msg) != length:
                raise ValueError(f"Incomplete message read from {filename}")

            yield msg


import pandas as pd
msg1 = read_dataset(DATA_FILE_PATH1)
msg2 = read_dataset(DATA_FILE_PATH2)
msglist1 = pd.DataFrame(msg)
msglist2 = pd.DataFrame(msg)
print(msg)
```

**Comment by cdecker** [comment]
`varint_decode` returns `None` at the end of the file, which could be causing the short reads, if `f.read(None)` silently works (which iirc means "read to the end" and so lengths will not match). So an additional `None` check is needed and a `break` if we're at the end of the file.

**Comment by cdecker** [comment]
Turns out that the september 2021 dump was not compressed, resulting in `bz2` throwing an exception. I'll compress and re-upload asap.
